### ISSUE TITLE
getting audio data without getting a cors error

### ISSUE THREAD

**Issue by ruvvet** [ruvvet/untitled-game#24]
Keep getting a cors error when trying to get frequency data from local audio files. Files hosted on servers seem to be fine though?

**Comment by romebell** [comment]
Which file are you fetching data?

**Comment by ruvvet** [comment]
It's a local file. Plays fine with normal audio tag. But the minute i try to get the data by calling my event listener it breaks

This is just a test page to try and fetch the datapoints
![image](https://user-images.githubusercontent.com/63803927/98170633-57c2c800-1ebc-11eb-922d-8c8d343a1351.png)
